#!/usr/bin/env bash
#
# G2X — apply the schema-patch fix on the VPS.
#
# Fixes: `npm run db:sellflow` failing with "no such column: unit_label".
#
# The Phase 19/20 columns lived only inside src/lib/ensure-schema.ts, which is a
# `server-only` module the CLI scripts cannot import. So db:migrate never added
# them and any seeder touching them crashed. This moves the list into a shared
# plain-JS module both sides can read, and makes the seeders self-heal.
#
# Safe to re-run. Touches no data.
#
set -euo pipefail
cd "$(dirname "$0")"

echo "==> backing up the files being replaced"
ts=$(date +%Y%m%d-%H%M%S)
for f in src/lib/ensure-schema.ts package.json; do
  [ -f "$f" ] && cp "$f" "$f.bak-$ts" && echo "    $f -> $f.bak-$ts"
done

echo "==> writing src/lib/schema-patches.mjs"
mkdir -p "$(dirname src/lib/schema-patches.mjs)"
base64 -d > "src/lib/schema-patches.mjs" <<'B64_EOF'
LyoqCiAqIEFERElUSVZFIFNDSEVNQSBQQVRDSEVTIOKAlCBzaW5nbGUgc291cmNlIG9mIHRydXRoLgogKgogKiBUaGVzZSBjb2x1bW5zL2luZGV4ZXMgYXJl
IGFkZGVkIGFmdGVyIHRoZSBiYXNlIHNjaGVtYS4gVGhleSBsaXZlIGhlcmUgYXMKICogcGxhaW4gZGF0YSBzbyBCT1RIIGNhbGxlcnMgdXNlIHRoZSBpZGVu
dGljYWwgbGlzdDoKICoKICogICAtIHNyYy9saWIvZW5zdXJlLXNjaGVtYS50cyAgKHJ1bnRpbWUgZ3VhcmQsIGluc2lkZSB0aGUgYXBwKQogKiAgIC0gc2Ny
aXB0cy9kZXBsb3ktbWlncmF0ZS5tdHMgKyBldmVyeSBzZWVkZXIgKENMSSwgb3V0c2lkZSB0aGUgYXBwKQogKgogKiBUaGV5IHVzZWQgdG8gZXhpc3Qgb25s
eSBpbnNpZGUgdGhlIGBzZXJ2ZXItb25seWAgbW9kdWxlLCB3aGljaCBtZWFudCBDTEkKICogc2NyaXB0cyBjb3VsZCBub3Qgc2VlIHRoZW06IGBucG0gcnVu
IGRiOnNlbGxmbG93YCB3b3VsZCBmYWlsIHdpdGgKICogIm5vIHN1Y2ggY29sdW1uOiB1bml0X2xhYmVsIiBvbiBhIGRhdGFiYXNlIHRoYXQgaGFkIG9ubHkg
YmVlbiB0aHJvdWdoCiAqIGBkYjpzZWVkYCArIGBkYjptaWdyYXRlYC4gS2VlcGluZyBvbmUgc2hhcmVkIGxpc3QgbWFrZXMgdGhhdCBpbXBvc3NpYmxlLgog
KgogKiBFdmVyeSBzdGF0ZW1lbnQgbXVzdCBiZSBhZGRpdGl2ZSBhbmQgaWRlbXBvdGVudCDigJQgY29sdW1ucyBhbmQgaW5kZXhlcyBvbmx5LAogKiBuZXZl
ciBhIGRyb3Agb3IgYSByZXdyaXRlLgogKi8KZXhwb3J0IGNvbnN0IFBBVENIRVMgPSBbCiAgYEFMVEVSIFRBQkxFIHRyYW5zYWN0aW9ucyBBREQgQ09MVU1O
IGlkZW1fa2V5IFRFWFRgLAogIGBDUkVBVEUgVU5JUVVFIElOREVYIElGIE5PVCBFWElTVFMgaWR4X3R4bl9pZGVtIE9OIHRyYW5zYWN0aW9ucyhpZGVtX2tl
eSlgLAogIGBBTFRFUiBUQUJMRSB1c2VycyBBREQgQ09MVU1OIGt5Y19kdWVfYXQgVEVYVGAsCiAgYEFMVEVSIFRBQkxFIHVzZXJzIEFERCBDT0xVTU4ga3lj
X2R1ZV9yZWFzb24gVEVYVGAsCiAgYENSRUFURSBJTkRFWCBJRiBOT1QgRVhJU1RTIGlkeF91c2Vyc19reWNfZHVlIE9OIHVzZXJzKGt5Y19kdWVfYXQpYCwK
CiAgLy8gLS0tIFBoYXNlIDE2OiB1c2VybmFtZXMgLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLQogIGBBTFRFUiBU
QUJMRSB1c2VycyBBREQgQ09MVU1OIHVzZXJuYW1lIFRFWFRgLAogIGBBTFRFUiBUQUJMRSB1c2VycyBBREQgQ09MVU1OIHVzZXJuYW1lX2NoYW5nZXMgSU5U
RUdFUiBOT1QgTlVMTCBERUZBVUxUIDBgLAogIGBDUkVBVEUgVU5JUVVFIElOREVYIElGIE5PVCBFWElTVFMgaWR4X3VzZXJzX3VzZXJuYW1lIE9OIHVzZXJz
KHVzZXJuYW1lKWAsCgogIC8vIC0tLSBQaGFzZSAxNjogNy1kYXkgZXNjcm93IGF1dG8tcmVsZWFzZSAtLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t
LS0KICBgQUxURVIgVEFCTEUgb3JkZXJzIEFERCBDT0xVTU4gZGVsaXZlcmVkX2F0IFRFWFRgLAogIGBBTFRFUiBUQUJMRSBvcmRlcnMgQUREIENPTFVNTiBy
ZWxlYXNlX2F0IFRFWFRgLAogIGBBTFRFUiBUQUJMRSBvcmRlcnMgQUREIENPTFVNTiByZWxlYXNlZCBJTlRFR0VSIE5PVCBOVUxMIERFRkFVTFQgMGAsCiAg
YENSRUFURSBJTkRFWCBJRiBOT1QgRVhJU1RTIGlkeF9vcmRlcnNfcmVsZWFzZSBPTiBvcmRlcnMocmVsZWFzZWQsIHJlbGVhc2VfYXQpYCwKCiAgLy8gLS0t
IFBoYXNlIDE2OiBjaGF0IGF0dGFjaG1lbnRzICsgaW4tdGhyZWFkIGRpc3B1dGVzIC0tLS0tLS0tLS0tLS0tLS0tLS0tLQogIGBBTFRFUiBUQUJMRSBtZXNz
YWdlcyBBREQgQ09MVU1OIGtpbmQgVEVYVCBOT1QgTlVMTCBERUZBVUxUICd0ZXh0J2AsCiAgYEFMVEVSIFRBQkxFIG1lc3NhZ2VzIEFERCBDT0xVTU4gYXR0
YWNobWVudF9uYW1lIFRFWFRgLAogIGBBTFRFUiBUQUJMRSBtZXNzYWdlcyBBREQgQ09MVU1OIGF0dGFjaG1lbnRfdHlwZSBURVhUYCwKICBgQUxURVIgVEFC
TEUgbWVzc2FnZXMgQUREIENPTFVNTiBhdHRhY2htZW50X3NpemUgSU5URUdFUmAsCiAgYEFMVEVSIFRBQkxFIG1lc3NhZ2VzIEFERCBDT0xVTU4gYXR0YWNo
bWVudF9kYXRhIFRFWFRgLAogIGBBTFRFUiBUQUJMRSBtZXNzYWdlcyBBREQgQ09MVU1OIGRpc3B1dGVfaWQgVEVYVGAsCiAgYEFMVEVSIFRBQkxFIHRocmVh
ZHMgQUREIENPTFVNTiBkaXNwdXRlX2lkIFRFWFRgLAogIGBBTFRFUiBUQUJMRSBkaXNwdXRlcyBBREQgQ09MVU1OIHRocmVhZF9pZCBURVhUYCwKCiAgLy8g
LS0tIFBoYXNlIDE4OiBzcGxpdCB3YWxsZXQgLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tCiAgLy8gYGJhbGFuY2VgIHN0
YXlzIHRoZSBzaW5nbGUgc3BlbmRhYmxlIG51bWJlci4gYHdpdGhkcmF3YWJsZWAgdHJhY2tzIGhvdwogIC8vIG11Y2ggb2YgaXQgY2FtZSBmcm9tIHNlbGxl
ciBlYXJuaW5ncyDigJQgdG9wcGVkLXVwIG1vbmV5IGNhbiBiZSBzcGVudCBidXQKICAvLyBuZXZlciBjYXNoZWQgb3V0LgogIGBBTFRFUiBUQUJMRSB1c2Vy
cyBBREQgQ09MVU1OIHdpdGhkcmF3YWJsZSBSRUFMIE5PVCBOVUxMIERFRkFVTFQgMGAsCgogIC8vIC0tLSBQaGFzZSAxODogc3Vic2NyaXB0aW9uIGRyaXAt
cmVsZWFzZSAtLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLQogIGBBTFRFUiBUQUJMRSBwcm9kdWN0cyBBREQgQ09MVU1OIHN1Yl9tb250aHMgSU5U
RUdFUiBOT1QgTlVMTCBERUZBVUxUIDBgLAogIGBBTFRFUiBUQUJMRSBvZmZlcnMgQUREIENPTFVNTiBzdWJfbW9udGhzIElOVEVHRVIgTk9UIE5VTEwgREVG
QVVMVCAwYCwKICBgQUxURVIgVEFCTEUgb3JkZXJfaXRlbXMgQUREIENPTFVNTiBzdWJfbW9udGhzIElOVEVHRVIgTk9UIE5VTEwgREVGQVVMVCAwYCwKICBg
Q1JFQVRFIFRBQkxFIElGIE5PVCBFWElTVFMgc3Vic2NyaXB0aW9uX3NjaGVkdWxlICgKICAgICBpZCBURVhUIFBSSU1BUlkgS0VZLAogICAgIG9yZGVyX2lk
IFRFWFQgTk9UIE5VTEwsCiAgICAgb3JkZXJfaXRlbV9pZCBURVhUIE5PVCBOVUxMLAogICAgIHNlbGxlcl9pZCBURVhUIE5PVCBOVUxMLAogICAgIGJ1eWVy
X2lkIFRFWFQgTk9UIE5VTEwsCiAgICAgbW9udGhfbm8gSU5URUdFUiBOT1QgTlVMTCwKICAgICBtb250aHNfdG90YWwgSU5URUdFUiBOT1QgTlVMTCwKICAg
ICBhbW91bnQgUkVBTCBOT1QgTlVMTCwKICAgICBkdWVfYXQgVEVYVCBOT1QgTlVMTCwKICAgICByZWxlYXNlZCBJTlRFR0VSIE5PVCBOVUxMIERFRkFVTFQg
MCwKICAgICByZWxlYXNlZF9hdCBURVhULAogICAgIGNyZWF0ZWRfYXQgVEVYVCBERUZBVUxUIChkYXRldGltZSgnbm93JykpCiAgIClgLAogIGBDUkVBVEUg
SU5ERVggSUYgTk9UIEVYSVNUUyBpZHhfc3ViX2R1ZSBPTiBzdWJzY3JpcHRpb25fc2NoZWR1bGUocmVsZWFzZWQsIGR1ZV9hdClgLAogIGBDUkVBVEUgSU5E
RVggSUYgTk9UIEVYSVNUUyBpZHhfc3ViX29yZGVyIE9OIHN1YnNjcmlwdGlvbl9zY2hlZHVsZShvcmRlcl9pZClgLAogIGBDUkVBVEUgVU5JUVVFIElOREVY
IElGIE5PVCBFWElTVFMgaWR4X3N1Yl9pdGVtX21vbnRoCiAgICAgT04gc3Vic2NyaXB0aW9uX3NjaGVkdWxlKG9yZGVyX2l0ZW1faWQsIG1vbnRoX25vKWAs
CgogIC8vIC0tLSBQaGFzZSAxODogZGlzcHV0ZSBjaGF0ICsgMTAtZGF5IG1lZGlhIHJldGVudGlvbiAtLS0tLS0tLS0tLS0tLS0tLS0tLQogIGBBTFRFUiBU
QUJMRSBkaXNwdXRlX21lc3NhZ2VzIEFERCBDT0xVTU4ga2luZCBURVhUIE5PVCBOVUxMIERFRkFVTFQgJ3RleHQnYCwKICBgQUxURVIgVEFCTEUgZGlzcHV0
ZV9tZXNzYWdlcyBBREQgQ09MVU1OIGF0dGFjaG1lbnRfbmFtZSBURVhUYCwKICBgQUxURVIgVEFCTEUgZGlzcHV0ZV9tZXNzYWdlcyBBREQgQ09MVU1OIGF0
dGFjaG1lbnRfdHlwZSBURVhUYCwKICBgQUxURVIgVEFCTEUgZGlzcHV0ZV9tZXNzYWdlcyBBREQgQ09MVU1OIGF0dGFjaG1lbnRfc2l6ZSBJTlRFR0VSYCwK
ICBgQUxURVIgVEFCTEUgZGlzcHV0ZV9tZXNzYWdlcyBBREQgQ09MVU1OIGF0dGFjaG1lbnRfZGF0YSBURVhUYCwKICBgQUxURVIgVEFCTEUgZGlzcHV0ZV9t
ZXNzYWdlcyBBREQgQ09MVU1OIHB1cmdlZCBJTlRFR0VSIE5PVCBOVUxMIERFRkFVTFQgMGAsCiAgYENSRUFURSBJTkRFWCBJRiBOT1QgRVhJU1RTIGlkeF9k
bXNnX2Rpc3B1dGUgT04gZGlzcHV0ZV9tZXNzYWdlcyhkaXNwdXRlX2lkLCBjcmVhdGVkX2F0KWAsCiAgYEFMVEVSIFRBQkxFIG1lc3NhZ2VzIEFERCBDT0xV
TU4gcHVyZ2VkIElOVEVHRVIgTk9UIE5VTEwgREVGQVVMVCAwYCwKCiAgLy8gLS0tIFBoYXNlIDE5OiBhZG1pbi1jb25maWd1cmFibGUgb2ZmZXIgd2l6YXJk
IC0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tCiAgYEFMVEVSIFRBQkxFIGNhdGVnb3JpZXMgQUREIENPTFVNTiBzZWxsX25vdGljZSBURVhUYCwKICBgQUxU
RVIgVEFCTEUgY2F0ZWdvcmllcyBBREQgQ09MVU1OIHNlbGxfbm90aWNlX3RpdGxlIFRFWFRgLAogIGBBTFRFUiBUQUJMRSBjYXRlZ29yaWVzIEFERCBDT0xV
TU4gdW5pdF9sYWJlbCBURVhUYCwKICBgQUxURVIgVEFCTEUgY2F0ZWdvcmllcyBBREQgQ09MVU1OIG5lZWRzX3RpdGxlIElOVEVHRVIgTk9UIE5VTEwgREVG
QVVMVCAwYCwKICBgQUxURVIgVEFCTEUgY2F0ZWdvcmllcyBBREQgQ09MVU1OIG5lZWRzX2ltYWdlcyBJTlRFR0VSIE5PVCBOVUxMIERFRkFVTFQgMGAsCiAg
YEFMVEVSIFRBQkxFIGNhdGVnb3JpZXMgQUREIENPTFVNTiBuZWVkc19jcmVkZW50aWFscyBJTlRFR0VSIE5PVCBOVUxMIERFRkFVTFQgMGAsCiAgYEFMVEVS
IFRBQkxFIGNhdGVnb3JpZXMgQUREIENPTFVNTiBuZWVkc19xdWFudGl0eSBJTlRFR0VSIE5PVCBOVUxMIERFRkFVTFQgMWAsCiAgYEFMVEVSIFRBQkxFIGNh
dGVnb3JpZXMgQUREIENPTFVNTiBhbGxvd192b2x1bWVfZGlzY291bnQgSU5URUdFUiBOT1QgTlVMTCBERUZBVUxUIDFgLAogIGBBTFRFUiBUQUJMRSBjYXRl
Z29yaWVzIEFERCBDT0xVTU4gY29tbWlzc2lvbl9wY3QgUkVBTGAsCiAgYEFMVEVSIFRBQkxFIG9mZmVycyBBREQgQ09MVU1OIHZvbHVtZV9kaXNjb3VudHMg
VEVYVGAsCiAgYEFMVEVSIFRBQkxFIG9mZmVycyBBREQgQ09MVU1OIGFjY291bnRzX2RhdGEgVEVYVGAsCiAgYEFMVEVSIFRBQkxFIG9mZmVycyBBREQgQ09M
VU1OIGltYWdlcyBURVhUYCwKICBgQUxURVIgVEFCTEUgb2ZmZXJzIEFERCBDT0xVTU4gZGVzY3JpcHRpb24gVEVYVGAsCiAgYEFMVEVSIFRBQkxFIG9mZmVy
cyBBREQgQ09MVU1OIG1pbl9xdHkgSU5URUdFUiBOT1QgTlVMTCBERUZBVUxUIDFgLAogIGBBTFRFUiBUQUJMRSBvZmZlcnMgQUREIENPTFVNTiBhdXRvX2Rl
bGl2ZXJ5IElOVEVHRVIgTk9UIE5VTEwgREVGQVVMVCAxYCwKCiAgLy8gLS0tIFBoYXNlIDIwOiBwZXItUFJPRFVDVCBzZWxsLWZsb3cgb3ZlcnJpZGVzIC0t
LS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tCiAgLy8gTlVMTCBtZWFucyAiaW5oZXJpdCB0aGUgY2F0ZWdvcnkgc2V0dGluZyIuCiAgYEFMVEVSIFRBQkxFIHBy
b2R1Y3RzIEFERCBDT0xVTU4gbmVlZHNfdGl0bGUgSU5URUdFUmAsCiAgYEFMVEVSIFRBQkxFIHByb2R1Y3RzIEFERCBDT0xVTU4gbmVlZHNfaW1hZ2VzIElO
VEVHRVJgLAogIGBBTFRFUiBUQUJMRSBwcm9kdWN0cyBBREQgQ09MVU1OIG5lZWRzX2NyZWRlbnRpYWxzIElOVEVHRVJgLAogIGBBTFRFUiBUQUJMRSBwcm9k
dWN0cyBBREQgQ09MVU1OIG5lZWRzX3F1YW50aXR5IElOVEVHRVJgLAogIGBBTFRFUiBUQUJMRSBwcm9kdWN0cyBBREQgQ09MVU1OIGFsbG93X3ZvbHVtZV9k
aXNjb3VudCBJTlRFR0VSYCwKICBgQUxURVIgVEFCTEUgcHJvZHVjdHMgQUREIENPTFVNTiB1bml0X2xhYmVsIFRFWFRgLAogIGBBTFRFUiBUQUJMRSBwcm9k
dWN0cyBBREQgQ09MVU1OIGNvbW1pc3Npb25fcGN0IFJFQUxgLAogIGBBTFRFUiBUQUJMRSBwcm9kdWN0cyBBREQgQ09MVU1OIGZ1bGZpbG1lbnQgVEVYVGAs
CiAgYEFMVEVSIFRBQkxFIHByb2R1Y3RzIEFERCBDT0xVTU4gc2hvd19kZWxpdmVyeV9tZXRob2QgSU5URUdFUmAsCiAgYEFMVEVSIFRBQkxFIHByb2R1Y3Rz
IEFERCBDT0xVTU4gc2hvd19yZWdpb24gSU5URUdFUmAsCiAgYEFMVEVSIFRBQkxFIHByb2R1Y3RzIEFERCBDT0xVTU4gc2hvd19wbGF0Zm9ybSBJTlRFR0VS
YCwKICBgQUxURVIgVEFCTEUgcHJvZHVjdHMgQUREIENPTFVNTiBzaG93X2xvZ2luX21ldGhvZCBJTlRFR0VSYCwKICBgQUxURVIgVEFCTEUgcHJvZHVjdHMg
QUREIENPTFVNTiBzZWxsX25vdGljZSBURVhUYCwKICBgQUxURVIgVEFCTEUgY2F0ZWdvcmllcyBBREQgQ09MVU1OIGZ1bGZpbG1lbnQgVEVYVGAsCiAgYEFM
VEVSIFRBQkxFIGNhdGVnb3JpZXMgQUREIENPTFVNTiBzaG93X2RlbGl2ZXJ5X21ldGhvZCBJTlRFR0VSIE5PVCBOVUxMIERFRkFVTFQgMWAsCiAgYEFMVEVS
IFRBQkxFIGNhdGVnb3JpZXMgQUREIENPTFVNTiBzaG93X3JlZ2lvbiBJTlRFR0VSIE5PVCBOVUxMIERFRkFVTFQgMWAsCiAgYEFMVEVSIFRBQkxFIGNhdGVn
b3JpZXMgQUREIENPTFVNTiBzaG93X3BsYXRmb3JtIElOVEVHRVIgTk9UIE5VTEwgREVGQVVMVCAxYCwKICBgQUxURVIgVEFCTEUgY2F0ZWdvcmllcyBBREQg
Q09MVU1OIHNob3dfbG9naW5fbWV0aG9kIElOVEVHRVIgTk9UIE5VTEwgREVGQVVMVCAxYCwKXTsKCi8qKiBFcnJvcnMgdGhhdCBtZWFuICJhbHJlYWR5IGFw
cGxpZWQiIOKAlCBleHBlY3RlZCBvbiBldmVyeSBydW4gYWZ0ZXIgdGhlIGZpcnN0LiAqLwpleHBvcnQgY29uc3QgaXNCZW5pZ25TY2hlbWFFcnJvciA9ICht
ZXNzYWdlKSA9PgogIC9kdXBsaWNhdGUgY29sdW1ufGFscmVhZHkgZXhpc3RzL2kudGVzdChTdHJpbmcobWVzc2FnZSA/PyAiIikpOwoKLyoqCiAqIEFwcGx5
IGV2ZXJ5IHBhdGNoIGFnYWluc3QgYSBsaWJTUUwgY2xpZW50LgogKiBOZXZlciB0aHJvd3M6IGEgcGF0Y2ggdGhhdCBjYW5ub3QgYXBwbHkgaXMgcmVwb3J0
ZWQsIG5vdCBmYXRhbC4KICovCmV4cG9ydCBhc3luYyBmdW5jdGlvbiBhcHBseVBhdGNoZXMoZGIsIHsgbG9nID0gZmFsc2UgfSA9IHt9KSB7CiAgbGV0IGFw
cGxpZWQgPSAwLCBwcmVzZW50ID0gMCwgZmFpbGVkID0gMDsKICBmb3IgKGNvbnN0IHNxbCBvZiBQQVRDSEVTKSB7CiAgICB0cnkgewogICAgICBhd2FpdCBk
Yi5leGVjdXRlKHNxbCk7CiAgICAgIGFwcGxpZWQrKzsKICAgIH0gY2F0Y2ggKGUpIHsKICAgICAgaWYgKGlzQmVuaWduU2NoZW1hRXJyb3IoZT8ubWVzc2Fn
ZSkpIHByZXNlbnQrKzsKICAgICAgZWxzZSB7CiAgICAgICAgZmFpbGVkKys7CiAgICAgICAgaWYgKGxvZykgY29uc29sZS53YXJuKGAgIHNraXBwZWQ6ICR7
c3FsLnNsaWNlKDAsIDYwKX0g4oCUICR7U3RyaW5nKGU/Lm1lc3NhZ2UpLnNsaWNlKDAsIDEwMCl9YCk7CiAgICAgIH0KICAgIH0KICB9CiAgcmV0dXJuIHsg
YXBwbGllZCwgcHJlc2VudCwgZmFpbGVkLCB0b3RhbDogUEFUQ0hFUy5sZW5ndGggfTsKfQo=
B64_EOF

echo "==> writing src/lib/ensure-schema.ts"
mkdir -p "$(dirname src/lib/ensure-schema.ts)"
base64 -d > "src/lib/ensure-schema.ts" <<'B64_EOF'
aW1wb3J0ICJzZXJ2ZXItb25seSI7CmltcG9ydCB7IGRiIH0gZnJvbSAiLi9kYiI7CmltcG9ydCB7IFBBVENIRVMsIGlzQmVuaWduU2NoZW1hRXJyb3IgfSBm
cm9tICIuL3NjaGVtYS1wYXRjaGVzLm1qcyI7CgovKioKICogUlVOVElNRSBTQ0hFTUEgR1VBUkQKICogPT09PT09PT09PT09PT09PT09PT0KICogQXBwbGll
cyB0aGUgYWRkaXRpdmUgcGF0Y2ggbGlzdCBvbiB0aGUgZmlyc3QgREItdG91Y2hpbmcgcmVxdWVzdCBpbiBhCiAqIHByb2Nlc3MsIHNvIGEgZnJlc2hseSBk
ZXBsb3llZCBidWlsZCByZXBhaXJzIGl0cyBvd24gZGF0YWJhc2UgaW5zdGVhZCBvZgogKiB0aHJvd2luZyAibm8gc3VjaCBjb2x1bW4iLgogKgogKiBUaGUg
c3RhdGVtZW50cyB0aGVtc2VsdmVzIGxpdmUgaW4gYHNjaGVtYS1wYXRjaGVzLm1qc2Ag4oCUIHBsYWluIGRhdGEsIG5vCiAqIGBzZXJ2ZXItb25seWAgaW1w
b3J0IOKAlCBzbyB0aGUgQ0xJIHNjcmlwdHMgY2FuIGFwcGx5IHRoZSBleGFjdCBzYW1lIGxpc3QuCiAqIFdoZW4gdGhlIGxpc3QgbGl2ZWQgaW4gaGVyZSwg
c2NyaXB0cyBjb3VsZCBub3QgcmVhZCBpdCBhbmQgYSBkYXRhYmFzZSB0aGF0CiAqIGhhZCBvbmx5IGJlZW4gc2VlZGVkICsgbWlncmF0ZWQgd2FzIG1pc3Np
bmcgZXZlcnkgUGhhc2UgMTkvMjAgY29sdW1uLgogKgogKiBDaGVhcCBieSBkZXNpZ246IHJ1bnMgb25jZSBwZXIgcHJvY2VzcywgdGhlbiBhIGNhY2hlZCBu
by1vcC4KICovCgpsZXQgZG9uZTogUHJvbWlzZTx2b2lkPiB8IG51bGwgPSBudWxsOwoKYXN5bmMgZnVuY3Rpb24gYXBwbHkoKTogUHJvbWlzZTx2b2lkPiB7
CiAgZm9yIChjb25zdCBzcWwgb2YgUEFUQ0hFUykgewogICAgdHJ5IHsKICAgICAgYXdhaXQgZGIuZXhlY3V0ZShzcWwpOwogICAgfSBjYXRjaCAoZSkgewog
ICAgICBjb25zdCBtc2cgPSBTdHJpbmcoKGUgYXMgRXJyb3IpPy5tZXNzYWdlID8/ICIiKTsKICAgICAgaWYgKGlzQmVuaWduU2NoZW1hRXJyb3IobXNnKSkg
Y29udGludWU7CiAgICAgIC8vIExvZ2dlZCwgbmV2ZXIgdGhyb3duOiBhIHNjaGVtYS1yZXBhaXIgZmFpbHVyZSBtdXN0IG5vdCB0YWtlIGRvd24gYQogICAg
ICAvLyByZXF1ZXN0IHRoYXQgbWlnaHQgbm90IGV2ZW4gbmVlZCB0aGUgbmV3IGNvbHVtbi4KICAgICAgY29uc29sZS53YXJuKGBbZW5zdXJlLXNjaGVtYV0g
c2tpcHBlZDogJHtzcWwuc2xpY2UoMCwgNjApfSDigJQgJHttc2cuc2xpY2UoMCwgMTIwKX1gKTsKICAgIH0KICB9Cn0KCi8qKgogKiBJZGVtcG90ZW50LCBj
b25jdXJyZW5jeS1zYWZlLCBvbmNlIHBlciBwcm9jZXNzLgogKiBBd2FpdGluZyB0aGlzIGZyb20gc2V2ZXJhbCByZXF1ZXN0cyBhdCBvbmNlIHJ1bnMgdGhl
IHBhdGNoZXMgYSBzaW5nbGUgdGltZS4KICovCmV4cG9ydCBmdW5jdGlvbiBlbnN1cmVTY2hlbWEoKTogUHJvbWlzZTx2b2lkPiB7CiAgaWYgKCFkb25lKSB7
CiAgICBkb25lID0gYXBwbHkoKS5jYXRjaCgoKSA9PiB7CiAgICAgIC8vIE5ldmVyIGNhY2hlIGEgcmVqZWN0aW9uIOKAlCBsZXQgYSBsYXRlciByZXF1ZXN0
IHJldHJ5LgogICAgICBkb25lID0gbnVsbDsKICAgIH0pIGFzIFByb21pc2U8dm9pZD47CiAgfQogIHJldHVybiBkb25lOwp9Cg==
B64_EOF

echo "==> adding the db:setup-vps script to package.json"
node -e '
const fs = require("fs");
const p = "package.json";
const d = JSON.parse(fs.readFileSync(p, "utf8"));
d.scripts["db:setup-vps"] =
  "npm run db:seed && npm run db:migrate && npm run db:ensure && " +
  "npm run db:options && npm run db:cms && npm run db:nav && " +
  "npm run db:gateways && npm run db:catalog-new && npm run db:sellflow && " +
  "npm run check:env";
d.scripts["db:backup"]  = d.scripts["db:backup"]  || "tsx scripts/backup-db.mts";
d.scripts["db:restore"] = d.scripts["db:restore"] || "tsx scripts/restore-db.mts";
fs.writeFileSync(p, JSON.stringify(d, null, 2) + "\n");
console.log("    db:setup-vps added");
'

echo "==> patching deploy-migrate to use the shared list"
node -e '
const fs = require("fs");
const p = "scripts/deploy-migrate.mts";
let s = fs.readFileSync(p, "utf8");
if (!s.includes("schema-patches.mjs")) {
  // Drop the old regex-based extractor and import the shared list instead.
  const i = s.indexOf("/** Pull the SQL statements out of");
  const j = s.indexOf("const benign =");
  if (i > -1 && j > i) s = s.slice(0, i) + s.slice(j);
  s = s.replace(/const benign = .*\n\n?/, "");
  s = s.replace("const list = patches();", "const list = PATCHES;");
  s = s.replace("if (benign(msg)) present++;", "if (isBenignSchemaError(msg)) present++;");
  s = s.replace(
    /import \{ readFileSync(, [^}]*)? \} from "node:fs";/,
    (m) => m.replace("readFileSync, ", "").replace("readFileSync", "existsSync, mkdirSync")
  );
  if (!s.includes("existsSync")) {
    s = s.replace(/^import /m, "import { existsSync, mkdirSync } from \"node:fs\";\nimport ");
  }
  s = s.replace(
    "import { resolveDbConfig } from \"./db-url.mjs\";",
    "import { resolveDbConfig } from \"./db-url.mjs\";\nimport { PATCHES, isBenignSchemaError } from \"../src/lib/schema-patches.mjs\";"
  );
  fs.writeFileSync(p, s);
  console.log("    deploy-migrate patched");
} else {
  console.log("    already patched");
}
'

echo "==> making the seeders self-heal"
node -e '
const fs = require("fs");
for (const p of ["scripts/seed-sellflow.mts","scripts/reseed-catalog.mts","scripts/seed-delivery-times.mts"]) {
  if (!fs.existsSync(p)) continue;
  let s = fs.readFileSync(p, "utf8");
  const hasImport = s.includes("schema-patches.mjs");
  const hasCall = /await applyPatches\(/.test(s);
  if (hasImport && hasCall) { console.log("    " + p + " already ok"); continue; }
  // Strip any half-applied state before re-patching.
  s = s.replace(/import \{ applyPatches \} from "\.\.\/src\/lib\/schema-patches\.mjs";\n/g, "");
  s = s.replace(/[ \t]*\/\/ Self-heal[^\n]*\n[ \t]*await applyPatches\(db\);\n/g, "");
  s = s.replace(
    /import \{ makeDb(, resolveDbConfig)? \} from ".\/db-url.mjs";/,
    (m) => m + "\nimport { applyPatches } from \"../src/lib/schema-patches.mjs\";"
  );
  s = s.replace(/async function main\(\)[^{]*\{\n/,
    (m) => m + "  // Self-heal the schema so command order cannot break this.\n  await applyPatches(db);\n");
  fs.writeFileSync(p, s);
  console.log("    " + p + " patched");
}
'

echo
echo "==> done. Now run:"
echo "      npm run db:setup-vps"
